name: cartesian_graph
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 1.2.5
  fraction: 1.2.1
  advanced_calculation:
    path: ../advanced_calculation

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.2
